import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,doc,getDocs,getFirestore,serverTimestamp,writeBatch}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const OWNER='shadrat.almn7@gmail.com',css=document.createElement('link');css.rel='stylesheet';css.href='admin-operations.css?v=3';document.head.appendChild(css);
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),main=document.querySelector('.admin-main');let users=[];
main.innerHTML=`<div class="admin-title"><div><span class="eyebrow">الحسابات والصلاحيات</span><h1>المستخدمون والفريق</h1></div></div><div class="admin-live-note"><b>إدارة فعلية مرتبطة بـFirebase:</b> راجع ملفات الطلاب، عدّل بياناتهم، عيّن فريق الدعم أو مشرف المجتمع، وعدّل XP بسبب موثق. أي XP أو تعديل مهم يرسل تنبيهًا للطالب تلقائيًا.</div><div class="admin-workspace"><div class="admin-toolbar"><div><h2>كل الحسابات</h2><small id="users-count">جارٍ التحميل…</small></div><div class="admin-toolbar-actions"><input id="users-search" placeholder="بحث بالاسم أو البريد"><select id="users-role"><option value="">كل الأدوار</option><option value="student">طلاب</option><option value="support">الدعم</option><option value="communityModerator">مشرفو المجتمع</option><option value="owner">المالك</option></select></div></div><section class="admin-form-panel" id="user-editor" hidden><h2>تعديل حساب</h2><form id="user-form"><input type="hidden" name="uid"><input type="hidden" name="oldXp"><div class="admin-form-grid"><label>الاسم الكامل<input name="fullName" required></label><label>الاسم الظاهر<input name="username" required></label><label>البريد<input name="email" disabled></label><label>آخر 4 أرقام للجوال<input name="phoneLast4" disabled></label><label>الدولة / المدينة<input name="location"></label><label>المرحلة الدراسية<input name="studyLevel"></label><label>الدور<select name="role"><option value="student">طالب</option><option value="support">دعم</option><option value="communityModerator">مشرف مجتمع</option><option value="owner">مالك</option></select></label><label>حالة الحساب<select name="accountStatus"><option value="active">نشط</option><option value="restricted">مقيّد</option><option value="suspended">موقوف</option></select></label><label>XP<input name="xp" type="number" min="0" max="9000"></label><label>المستوى<input name="level" disabled></label><label class="wide">سبب التعديل<textarea name="reason" placeholder="مثال: تصحيح الملف أو اعتماد إنجاز"></textarea></label></div><p class="admin-status"></p><div class="admin-form-actions"><button class="btn primary">حفظ التعديلات</button><button class="btn outline" type="button" data-close>إلغاء</button></div></form></section><div class="desktop-table-wrap"><table class="live-admin-table"><thead><tr><th>المستخدم</th><th>الدور</th><th>الحالة</th><th>XP</th><th>المستوى</th><th>الجوال</th><th>إجراء</th></tr></thead><tbody id="users-body"></tbody></table></div></div>`;
const body=document.querySelector('#users-body'),editor=document.querySelector('#user-editor'),form=document.querySelector('#user-form'),status=form.querySelector('.admin-status'),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),owner=u=>u.email===OWNER||u.role==='owner',level=x=>Math.min(10,Math.floor(Number(x||0)/1000)+1);
function filtered(){const q=document.querySelector('#users-search').value.trim().toLowerCase(),r=document.querySelector('#users-role').value;return users.filter(u=>(!r||u.role===r)&&(!q||[u.fullName,u.username,u.email].some(v=>String(v||'').toLowerCase().includes(q))))}
function render(){const list=filtered();document.querySelector('#users-count').textContent=`${list.length} حساب`;body.innerHTML=list.length?list.map(u=>`<tr><td data-label="المستخدم"><b>${esc(u.fullName||'بدون اسم')}</b><br><small>${esc(u.email||'')}</small><br><small>@${esc(u.username||'')}</small></td><td data-label="الدور"><span class="admin-pill">${esc(u.role||'student')}</span></td><td data-label="الحالة">${esc(u.accountStatus||'active')}</td><td data-label="XP">${Number(u.xp||0).toLocaleString('ar')}</td><td data-label="المستوى">${level(u.xp)}</td><td data-label="الجوال">${u.phoneLast4?`•••• ${esc(u.phoneLast4)}`:'—'}</td><td data-label="إجراء"><button class="admin-action" data-user="${esc(u.uid)}">فتح الملف</button></td></tr>`).join(''):'<tr><td colspan="7">لا توجد حسابات مطابقة.</td></tr>';body.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>open(users.find(u=>u.uid===b.dataset.user)))}
function open(u){form.reset();for(const k of['uid','fullName','username','email','phoneLast4','location','studyLevel','role','accountStatus','xp','oldXp'])if(form.elements[k])form.elements[k].value=k==='oldXp'?(u.xp||0):(u[k]??'');form.level.value=level(u.xp);form.role.disabled=owner(u);form.accountStatus.disabled=owner(u);editor.hidden=false;editor.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('#users-search').oninput=render;document.querySelector('#users-role').onchange=render;form.querySelector('[data-close]').onclick=()=>editor.hidden=true;form.xp.oninput=()=>form.level.value=level(form.xp.value);
form.onsubmit=async e=>{e.preventDefault();const current=users.find(u=>u.uid===form.uid.value);if(!current)return;const newXp=Math.max(0,Math.min(9000,Number(form.xp.value||0))),oldXp=Number(form.oldXp.value||0),reason=form.reason.value.trim(),roleChanged=form.role.value!==current.role,statusChanged=form.accountStatus.value!==current.accountStatus,changed=newXp!==oldXp||roleChanged||statusChanged;if(changed&&reason.length<3){status.textContent='اكتب سببًا واضحًا للتعديل الإداري.';return}status.textContent='جارٍ الحفظ…';try{const batch=writeBatch(db),isOwner=owner(current),newLevel=level(newXp);batch.update(doc(db,'users',current.uid),{fullName:form.fullName.value.trim(),username:form.username.value.trim().toLowerCase(),location:form.location.value.trim(),studyLevel:form.studyLevel.value.trim(),role:isOwner?'owner':form.role.value,accountStatus:isOwner?'active':form.accountStatus.value,xp:newXp,level:newLevel,updatedAt:serverTimestamp(),lastAdminEditReason:reason||'تصحيح بيانات الملف'});if(newXp!==oldXp){batch.set(doc(collection(db,'xpTransactions')),{userId:current.uid,points:newXp-oldXp,previousXp:oldXp,newXp,reason,reference:'owner_manual_adjustment',status:'approved',createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});batch.set(doc(collection(db,'users',current.uid,'notifications')),{title:newXp>oldXp?'تمت إضافة XP إلى حسابك':'تم تعديل رصيد XP',body:`رصيدك الآن ${newXp} XP — Level ${newLevel}.${reason?` السبب: ${reason}`:''}`,type:'xp',read:false,createdAt:serverTimestamp()})}else if(roleChanged||statusChanged){batch.set(doc(collection(db,'users',current.uid,'notifications')),{title:'تحديث على حسابك',body:reason||'قامت الإدارة بتحديث إعدادات حسابك.',type:'account',read:false,createdAt:serverTimestamp()})}await batch.commit();status.textContent='تم حفظ الحساب وإرسال التنبيه للطالب.';await load();setTimeout(()=>editor.hidden=true,700)}catch(err){console.error(err);status.textContent='تعذر الحفظ. تحقق من دخول حساب المالك وقواعد Firebase.'}};
async function load(){const s=await getDocs(collection(db,'users'));users=s.docs.map(d=>({uid:d.id,...d.data()}));const wanted=new URLSearchParams(location.search).get('uid');if(wanted){const found=users.find(x=>x.uid===wanted);if(found)open(found)}render()}
onAuthStateChanged(auth,u=>{if(u)load().catch(err=>{console.error(err);body.innerHTML='<tr><td colspan="7">تعذر تحميل الحسابات.</td></tr>'})});
