import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,doc,getDocs,getFirestore,serverTimestamp,updateDoc}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const OWNER='shadrat.almn7@gmail.com',STAFF_ROLES=['editor','support','communityModerator','admin'];
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let users=[];
const body=document.querySelector('#staff-body'),search=document.querySelector('#staff-search'),count=document.querySelector('#staff-count'),editor=document.querySelector('#staff-editor'),form=document.querySelector('#staff-form'),status=form.querySelector('.admin-status'),help=document.querySelector('#role-help'),candidateSearch=document.querySelector('#candidate-search'),candidateResults=document.querySelector('#candidate-results');
const roleText={student:'إزالة الرتبة الإدارية وإرجاع الحساب كطالب عادي.',editor:'محرر محتوى — يدير المنح والخدمات والعروض والفيديوهات.',support:'دعم وخدمة طلاب — يتعامل مع الطلبات والرسائل وملفات الطلاب اللازمة للدعم.',communityModerator:'مشرف مجتمع — يدير المنشورات والتعليقات والبلاغات.',admin:'مدير — صلاحيات إدارية واسعة مع بقاء حساب المالك محميًا.'};
const roleName={editor:'محرر محتوى',support:'دعم وخدمة طلاب',communityModerator:'مشرف مجتمع',admin:'مدير'};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function staffList(){const q=search.value.trim().toLowerCase();return users.filter(u=>u.email!==OWNER&&STAFF_ROLES.includes(u.role)&&(!q||[u.fullName,u.email,u.username,roleName[u.role]].some(v=>String(v||'').toLowerCase().includes(q))))}
function renderStaff(){const list=staffList();count.textContent=`${list.length} موظف`;body.innerHTML=list.map(u=>`<tr><td><b>${esc(u.fullName||u.username||'بدون اسم')}</b><br><small>${esc(u.email||'')}</small></td><td><span class="admin-pill">${esc(roleName[u.role]||u.role)}</span></td><td>${esc(u.accountStatus||'active')}</td><td><button class="admin-action" data-staff-uid="${esc(u.uid)}">تعديل الرتبة</button></td></tr>`).join('')||'<tr><td colspan="4">لا يوجد موظفون حتى الآن. أضف رتبة لحساب من الأسفل وسيظهر هنا.</td></tr>';body.querySelectorAll('[data-staff-uid]').forEach(b=>b.onclick=()=>open(users.find(u=>u.uid===b.dataset.staffUid)))}
function renderCandidates(){const q=candidateSearch.value.trim().toLowerCase();if(q.length<2){candidateResults.innerHTML='<p class="muted">اكتب حرفين على الأقل للبحث في الحسابات المسجلة.</p>';return}const list=users.filter(u=>u.email!==OWNER&&!STAFF_ROLES.includes(u.role)&&[u.fullName,u.email,u.username].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,8);candidateResults.innerHTML=list.length?list.map(u=>`<button type="button" class="admin-action" style="display:block;width:100%;text-align:right;margin:8px 0;padding:12px" data-candidate-uid="${esc(u.uid)}"><b>${esc(u.fullName||u.username||'بدون اسم')}</b><br><small>${esc(u.email||'')}</small></button>`).join(''):'<p class="muted">لا يوجد حساب مطابق أو أن الحساب موظف بالفعل.</p>';candidateResults.querySelectorAll('[data-candidate-uid]').forEach(b=>b.onclick=()=>open(users.find(u=>u.uid===b.dataset.candidateUid)))}
function open(u){if(!u||u.email===OWNER)return;form.reset();form.uid.value=u.uid;form.fullName.value=u.fullName||'';form.email.value=u.email||'';form.role.value=STAFF_ROLES.includes(u.role)?u.role:'editor';help.textContent=roleText[form.role.value];editor.hidden=false;editor.scrollIntoView({behavior:'smooth',block:'start'})}
form.role.onchange=()=>help.textContent=roleText[form.role.value];form.querySelector('[data-close]').onclick=()=>editor.hidden=true;search.oninput=renderStaff;candidateSearch.oninput=renderCandidates;
form.onsubmit=async e=>{e.preventDefault();const u=users.find(x=>x.uid===form.uid.value);if(!u||u.email===OWNER)return;status.textContent='جارٍ الحفظ…';try{await updateDoc(doc(db,'users',u.uid),{role:form.role.value,staffRoleUpdatedAt:serverTimestamp(),staffRoleUpdatedBy:auth.currentUser.uid,staffRoleReason:form.reason.value.trim()});status.textContent=form.role.value==='student'?'تمت إزالة الحساب من الموظفين.':'تم حفظ رتبة الموظف.';await load();setTimeout(()=>editor.hidden=true,450)}catch(err){console.error(err);status.textContent='تعذر الحفظ. يجب نشر قواعد Firebase المحدثة أولًا.'}};
async function load(){const s=await getDocs(collection(db,'users'));users=s.docs.map(d=>({uid:d.id,...d.data()}));renderStaff();renderCandidates()}
onAuthStateChanged(auth,u=>{if(u)load().catch(e=>{console.error(e);count.textContent='تعذر تحميل الموظفين';body.innerHTML='<tr><td colspan="4">Firebase رفض قراءة الحسابات. يلزم نشر قواعد Firestore المحدثة.</td></tr>'})});
