import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,getDocs,getFirestore}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const css=document.createElement('style');css.textContent=`.student-admin-toolbar{display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px;margin:16px 0 20px}.student-admin-toolbar input,.student-admin-toolbar select{width:100%;padding:12px 14px;border:1px solid #ded5c7;border-radius:13px;background:#fff;font:inherit}.student-cards{display:grid;gap:10px}.student-card{border:1px solid #e5ddce;border-radius:17px;background:#fffdf8;overflow:hidden}.student-card-head{width:100%;border:0;background:transparent;padding:15px 17px;display:flex;align-items:center;gap:13px;text-align:right;font:inherit;cursor:pointer}.student-avatar-mini{width:44px;height:44px;border-radius:13px;background:#e6f2ec;color:#176b4b;display:grid;place-items:center;font-weight:900;flex:0 0 44px}.student-main{min-width:0;flex:1}.student-main b,.student-main small{display:block}.student-main small{color:#68766f;direction:ltr;text-align:right;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.student-card-meta{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.student-mini-pill{padding:5px 9px;border-radius:99px;background:#f6ead1;color:#6f5320;font-size:11px;font-weight:800}.student-chevron{font-size:20px;transition:.2s}.student-card.open .student-chevron{transform:rotate(180deg)}.student-card-body{display:none;padding:0 17px 17px;border-top:1px solid #eee7db}.student-card.open .student-card-body{display:block}.student-details{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding-top:14px}.student-details div{padding:10px;border:1px solid #eee7db;border-radius:12px}.student-details small{display:block;color:#68766f}.student-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}@media(max-width:760px){.student-admin-toolbar{grid-template-columns:1fr}.student-card-head{align-items:flex-start}.student-card-meta{display:none}.student-details{grid-template-columns:1fr 1fr}}`;document.head.appendChild(css);
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),main=document.querySelector('.admin-main');let users=[];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),level=x=>Math.min(10,Math.floor(Math.max(0,Number(x||0))/1000)+1),statusLabel=s=>({active:'نشط',restricted:'مقيّد',suspended:'موقوف'}[s]||s||'نشط');
main.innerHTML=`<div class="admin-title"><div><span class="eyebrow">إدارة الطلاب</span><h1>الطلاب</h1><p class="muted">ابحث بالاسم أو اليوزر، افتح بطاقة الطالب ثم ادخل ملفه الإداري الكامل.</p></div></div><div class="admin-workspace"><div class="student-admin-toolbar"><input id="students-search" placeholder="ابحث باسم الطالب أو @username أو البريد"><select id="students-status"><option value="">كل الحالات</option><option value="active">نشط</option><option value="restricted">مقيّد</option><option value="suspended">موقوف</option></select><select id="students-level"><option value="">كل المستويات</option>${Array.from({length:10},(_,i)=>`<option value="${i+1}">Level ${i+1}</option>`).join('')}</select></div><div id="students-count" class="muted"></div><div class="student-cards" id="student-cards"></div></div>`;
const cards=document.querySelector('#student-cards'),search=document.querySelector('#students-search'),status=document.querySelector('#students-status'),levelFilter=document.querySelector('#students-level');
function filtered(){const q=search.value.trim().toLowerCase().replace(/^@/,'');return users.filter(u=>(u.role||'student')==='student'&&(!status.value||u.accountStatus===status.value)&&(!levelFilter.value||level(u.xp)===Number(levelFilter.value))&&(!q||[u.fullName,u.username,u.email].some(v=>String(v||'').toLowerCase().includes(q))))}
function render(){const list=filtered();document.querySelector('#students-count').textContent=`${list.length.toLocaleString('ar')} طالب`;cards.innerHTML=list.length?list.map(u=>`<article class="student-card" data-card="${esc(u.uid)}"><button class="student-card-head" type="button" data-toggle="${esc(u.uid)}"><span class="student-avatar-mini">${esc((u.fullName||u.username||'ط').trim().slice(0,1))}</span><span class="student-main"><b>${esc(u.fullName||'بدون اسم')}</b><small>@${esc(u.username||'—')}</small></span><span class="student-card-meta"><span class="student-mini-pill">Level ${level(u.xp)}</span><span class="student-mini-pill">${Number(u.xp||0).toLocaleString('ar')} XP</span><span class="student-mini-pill">${esc(statusLabel(u.accountStatus))}</span></span><span class="student-chevron">⌄</span></button><div class="student-card-body"><div class="student-details"><div><small>البريد</small><b dir="ltr">${esc(u.email||'—')}</b></div><div><small>الدولة / المدينة</small><b>${esc(u.location||'—')}</b></div><div><small>المرحلة</small><b>${esc(u.studyLevel||'—')}</b></div><div><small>آخر 4 من الجوال</small><b>${u.phoneLast4?`•••• ${esc(u.phoneLast4)}`:'—'}</b></div></div><div class="student-actions"><a class="btn primary" href="admin-student.html?uid=${encodeURIComponent(u.uid)}">فتح الملف الإداري</a><a class="btn outline" href="student-profile.html?uid=${encodeURIComponent(u.uid)}" target="_blank">الملف العام</a></div></div></article>`).join(''):'<div class="card" style="padding:20px">لا يوجد طلاب مطابقون للبحث.</div>';cards.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>document.querySelector(`[data-card="${CSS.escape(b.dataset.toggle)}"]`)?.classList.toggle('open'))}
[search,status,levelFilter].forEach(el=>el.addEventListener(el===search?'input':'change',render));
async function load(){const s=await getDocs(collection(db,'users'));users=s.docs.map(d=>({uid:d.id,...d.data()}));render()}
onAuthStateChanged(auth,u=>{if(u)load().catch(e=>{console.error(e);cards.innerHTML='<div class="card" style="padding:20px">تعذر تحميل الطلاب.</div>'})});
