import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,getDocs,getFirestore}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const css=document.createElement('style');css.textContent=`
.student-toolbar{display:grid;grid-template-columns:minmax(0,2fr) minmax(180px,1fr);gap:10px;margin:16px 0}.student-toolbar input,.student-toolbar select{width:100%;padding:13px 14px;border:1px solid #ded5c7;border-radius:13px;background:#fff;font:inherit}.student-list{display:grid;gap:10px}.student-row{display:grid;grid-template-columns:54px minmax(0,1.7fr) minmax(180px,1fr) auto;align-items:center;gap:14px;padding:14px 16px;border:1px solid #e6ded1;border-radius:16px;background:#fffdf9;text-decoration:none;color:inherit;transition:.15s}.student-row:hover{transform:translateY(-1px);border-color:#b9cfc3;box-shadow:0 8px 22px rgba(32,58,45,.06)}.student-avatar{width:48px;height:48px;border-radius:14px;background:#e6f2ec;color:#176b4b;display:grid;place-items:center;font-weight:900;font-size:18px}.student-identity{min-width:0}.student-identity b,.student-identity small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.student-identity small{color:#68766f;direction:ltr;text-align:right;margin-top:3px}.student-email{min-width:0;color:#58655f;direction:ltr;text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.student-meta{display:flex;gap:7px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.student-pill{padding:6px 9px;border-radius:999px;background:#f5ecdc;color:#6a5125;font-size:11px;font-weight:800;white-space:nowrap}.student-open{font-weight:900;color:#176b4b;white-space:nowrap}.students-empty{padding:22px;border:1px dashed #d8cfc1;border-radius:16px;background:#fffdf9}.students-error{padding:18px;border:1px solid #ecc9c5;border-radius:14px;background:#fff7f6;color:#8f2e27}@media(max-width:760px){.student-toolbar{grid-template-columns:1fr}.student-row{grid-template-columns:48px minmax(0,1fr) auto}.student-email{display:none}.student-meta{grid-column:2/-1;justify-content:flex-start}.student-open{align-self:start}}
`;document.head.appendChild(css);
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),main=document.querySelector('.admin-main');let users=[];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusLabel=s=>({active:'نشط',restricted:'مقيّد',suspended:'موقوف'}[s]||s||'نشط');
main.innerHTML=`<div class="admin-title"><div><span class="eyebrow">إدارة الطلاب</span><h1>حسابات الطلاب</h1><p class="muted">كل طالب يظهر كسجل واضح. اضغط على الحساب لفتح ملفه الإداري الكامل وتعديل بياناته.</p></div></div><div class="admin-workspace"><div class="student-toolbar"><input id="students-search" placeholder="ابحث بالاسم أو @username أو البريد"><select id="students-status"><option value="">كل الحالات</option><option value="active">نشط</option><option value="restricted">مقيّد</option><option value="suspended">موقوف</option></select></div><div id="students-count" class="muted" style="margin-bottom:10px"></div><div class="student-list" id="student-list"></div></div>`;
const listEl=document.querySelector('#student-list'),search=document.querySelector('#students-search'),status=document.querySelector('#students-status'),count=document.querySelector('#students-count');
function filtered(){const q=search.value.trim().toLowerCase().replace(/^@/,'');return users.filter(u=>(u.role||'student')==='student'&&(!status.value||u.accountStatus===status.value)&&(!q||[u.fullName,u.username,u.email].some(v=>String(v||'').toLowerCase().includes(q))))}
function render(){const list=filtered();count.textContent=`${list.length.toLocaleString('ar')} طالب`;listEl.innerHTML=list.length?list.map(u=>`<a class="student-row" href="admin-student.html?uid=${encodeURIComponent(u.uid)}"><span class="student-avatar">${esc((u.fullName||u.username||'ط').trim().slice(0,1))}</span><span class="student-identity"><b>${esc(u.fullName||'بدون اسم')}</b><small>@${esc(u.username||'—')}</small></span><span class="student-email">${esc(u.email||'—')}</span><span class="student-meta"><span class="student-pill">${Number(u.xp||0).toLocaleString('ar')} XP</span><span class="student-pill">${esc(statusLabel(u.accountStatus))}</span><span class="student-open">فتح الملف ←</span></span></a>`).join(''):'<div class="students-empty">لا يوجد طلاب مطابقون للبحث.</div>'}
search.addEventListener('input',render);status.addEventListener('change',render);
async function load(){const s=await getDocs(collection(db,'users'));users=s.docs.map(d=>({uid:d.id,...d.data()}));render()}
onAuthStateChanged(auth,u=>{if(u)load().catch(e=>{console.error(e);count.textContent='';listEl.innerHTML='<div class="students-error"><b>تعذر تحميل حسابات الطلاب.</b><br>كود الصفحة جاهز، لكن Firebase يرفض القراءة حتى يتم نشر قواعد Firestore المحدثة.</div>'})});
