import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,doc,getDoc,getDocs,getFirestore,query,serverTimestamp,updateDoc,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{getAuth}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),root=document.querySelector('#student-admin-root'),uid=new URLSearchParams(location.search).get('uid');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const level=x=>Math.min(10,Math.floor(Math.max(0,Number(x||0))/1000)+1);
const statusArabic=s=>({active:'نشط',restricted:'مقيّد',suspended:'موقوف',created:'جديد',waiting_info:'بانتظار المعلومات',under_review:'قيد المراجعة',in_progress:'قيد التنفيذ',action_needed:'يحتاج إجراء',completed:'مكتمل',canceled:'ملغي'}[s]||s||'—');
async function safeQuery(name){try{const s=await getDocs(query(collection(db,name),where('userId','==',uid)));return s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn(name,e);return[]}}
async function load(){if(!uid){root.innerHTML='<div class="card" style="padding:24px">لم يتم تحديد طالب.</div>';return}const snap=await getDoc(doc(db,'users',uid));if(!snap.exists()){root.innerHTML='<div class="card" style="padding:24px">الحساب غير موجود.</div>';return}const u={uid,...snap.data()},[orders,messages,xp]=await Promise.all([safeQuery('orders'),safeQuery('messages'),safeQuery('xpTransactions')]);
root.innerHTML=`<div class="admin-title"><div><span class="eyebrow">ملف الطالب الإداري</span><h1>${esc(u.fullName||u.username||'طالب')}</h1><p class="muted">@${esc(u.username||'—')} · ${esc(u.email||'')}</p></div><div class="student-admin-actions"><a class="btn outline" href="admin-users.html">رجوع للطلاب</a></div></div>
<div class="student-admin-grid"><section class="card student-admin-card"><h2>بيانات الحساب</h2><div class="student-admin-info"><div><small>البريد</small><b dir="ltr">${esc(u.email||'—')}</b></div><div><small>الجوال</small><b>${u.phoneLast4?`•••• ${esc(u.phoneLast4)}`:'—'}</b></div><div><small>الموقع</small><b>${esc(u.location||'—')}</b></div><div><small>المرحلة</small><b>${esc(u.studyLevel||'—')}</b></div><div><small>الحالة</small><b>${esc(statusArabic(u.accountStatus))}</b></div><div><small>الدور</small><b>${esc(u.role||'student')}</b></div><div><small>XP</small><b>${Number(u.xp||0).toLocaleString('ar')} XP</b></div><div><small>المستوى</small><b>Level ${level(u.xp)}</b></div></div></section>
<section class="card student-admin-card"><h2>ملخص النشاط</h2><div class="student-admin-info"><div><small>طلبات الخدمات</small><b>${orders.length}</b></div><div><small>رسائل الدعم</small><b>${messages.length}</b></div><div><small>معاملات XP</small><b>${xp.length}</b></div><div><small>آخر تعديل</small><b>${u.updatedAt?.toDate?u.updatedAt.toDate().toLocaleDateString('ar-SA'):'—'}</b></div></div></section></div>
<section class="card student-admin-card" style="margin-top:18px"><h2>تعديل الملف الإداري</h2><form id="admin-student-form"><div class="admin-edit-grid"><label>الاسم الكامل<input name="fullName" value="${esc(u.fullName||'')}" required></label><label>اليوزر<input name="username" value="${esc(u.username||'')}" dir="ltr" required pattern="[a-z0-9_]{3,24}"></label><label>الدولة / المدينة<input name="location" value="${esc(u.location||'')}"></label><label>المرحلة الدراسية<input name="studyLevel" value="${esc(u.studyLevel||'')}"></label><label>XP<input name="xp" type="number" min="0" max="9000" value="${Number(u.xp||0)}"></label><label>حالة الحساب<select name="accountStatus"><option value="active">نشط</option><option value="restricted">مقيّد</option><option value="suspended">موقوف</option></select></label><label>الدور<select name="role"><option value="student">طالب</option><option value="support">دعم</option><option value="editor">محرر</option><option value="communityModerator">مشرف مجتمع</option><option value="admin">مدير</option></select></label><label>سبب التعديل<input name="reason" placeholder="سبب واضح عند تعديل XP أو الحالة"></label></div><p class="admin-status" id="student-save-status"></p><div class="student-admin-actions" style="margin-top:14px"><button class="btn primary">حفظ التعديلات</button></div></form></section>
<div class="student-admin-grid" style="margin-top:18px"><section class="card student-admin-card"><h2>طلبات الطالب</h2><div class="student-admin-list">${orders.length?orders.map(o=>`<div class="student-admin-row"><b>${esc(o.serviceTitle||'طلب خدمة')}</b><br><small>${esc(statusArabic(o.status))} · ${Number(o.price||0)}$</small></div>`).join(''):'<p class="muted">لا توجد طلبات.</p>'}</div></section><section class="card student-admin-card"><h2>رسائل الطالب</h2><div class="student-admin-list">${messages.length?messages.map(m=>`<div class="student-admin-row"><b>${esc(m.type||'رسالة')}</b><br><small>${esc((m.message||'').slice(0,100))}</small></div>`).join(''):'<p class="muted">لا توجد رسائل.</p>'}</div></section></div>`;
const form=document.querySelector('#admin-student-form'),st=document.querySelector('#student-save-status');form.accountStatus.value=u.accountStatus||'active';form.role.value=u.role||'student';if(u.role==='owner'||u.email==='shadrat.almn7@gmail.com'){form.role.disabled=true;form.accountStatus.disabled=true}
form.onsubmit=async e=>{e.preventDefault();const reason=form.reason.value.trim(),newXp=Number(form.xp.value||0);if((newXp!==Number(u.xp||0)||form.accountStatus.value!==(u.accountStatus||'active'))&&reason.length<3){st.textContent='اكتب سببًا واضحًا للتعديل.';return}st.textContent='جارٍ الحفظ…';try{await updateDoc(doc(db,'users',uid),{fullName:form.fullName.value.trim(),username:form.username.value.trim().toLowerCase(),location:form.location.value.trim(),studyLevel:form.studyLevel.value.trim(),xp:newXp,level:level(newXp),accountStatus:u.role==='owner'?'active':form.accountStatus.value,role:u.role==='owner'?'owner':form.role.value,updatedAt:serverTimestamp(),lastAdminEditReason:reason||'تعديل إداري'});st.textContent='تم حفظ التعديلات.';setTimeout(load,500)}catch(err){console.error(err);st.textContent=err?.code==='permission-denied'?'ليس لهذا الحساب الإداري صلاحية تعديل هذه البيانات.':'تعذر الحفظ الآن.'}}
}
load().catch(e=>{console.error(e);root.innerHTML='<div class="card" style="padding:24px">تعذر تحميل ملف الطالب.</div>'});
