(()=>{
 const ID='G-XEXLP7S36Z',KEY='shazarat_analytics_consent',choice=localStorage.getItem(KEY);
 window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){dataLayer.push(arguments)};
 gtag('consent','default',{analytics_storage:choice==='granted'?'granted':'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',wait_for_update:500});
 if(!document.querySelector(`script[src*="${ID}"]`)){const s=document.createElement('script');s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${ID}`;document.head.appendChild(s)}
 gtag('js',new Date());gtag('config',ID,{anonymize_ip:true,send_page_view:true});
 const bindEvents=()=>{if(window.__shazaratGaBound)return;window.__shazaratGaBound=true;const path=location.pathname.split('/').pop()||'index.html';if(/open-doors|education-in-russia|turkiye-scholarships|stipendium-hungaricum|hse-scholarship|rudn-scholarship|nsu-scholarship/.test(path))gtag('event','scholarship_view',{scholarship_slug:path.replace('.html','')});document.addEventListener('click',e=>{const a=e.target.closest('a,button');if(!a)return;const text=(a.textContent||'').trim().slice(0,80),href=a.getAttribute('href')||'';if(a.matches('.official')||/المصدر|الموقع الرسمي/.test(text))gtag('event','official_source_click',{link_url:href,link_text:text});if(/اطلب الخدمة|طلب الخدمة/.test(text))gtag('event','service_request_start',{service_name:text})});document.addEventListener('submit',e=>{if(e.target.closest('#contact-form,[data-contact-form]'))gtag('event','contact_submit')})};bindEvents();
 if(choice)return;
 const box=document.createElement('div');box.dir='rtl';box.style.cssText='position:fixed;z-index:3000;right:14px;bottom:14px;width:min(430px,calc(100% - 28px));padding:17px;border:1px solid #ddcfb8;border-radius:18px;background:#fffdf8;color:#17352b;box-shadow:0 18px 55px #0003;font:14px/1.7 Tahoma,Arial';box.innerHTML='<b>خصوصية الإحصاءات</b><div>نستخدم Google Analytics لقياس الزيارات وتحسين المنصة دون بيع بياناتك.</div><div style="display:flex;gap:8px;margin-top:11px"><button data-ga-yes style="border:0;border-radius:11px;padding:9px 15px;background:#176b4b;color:#fff;font:inherit;font-weight:bold">موافق</button><button data-ga-no style="border:1px solid #d8cdbc;border-radius:11px;padding:9px 15px;background:#fff;color:#17352b;font:inherit">رفض</button><a href="privacy.html" style="padding:9px;color:#176b4b">السياسة</a></div>';document.body.appendChild(box);
 box.querySelector('[data-ga-yes]').onclick=()=>{localStorage.setItem(KEY,'granted');gtag('consent','update',{analytics_storage:'granted'});gtag('event','page_view');box.remove()};box.querySelector('[data-ga-no]').onclick=()=>{localStorage.setItem(KEY,'denied');gtag('consent','update',{analytics_storage:'denied'});box.remove()};
})();
