import { getApp, getApps, initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { browserLocalPersistence, createUserWithEmailAndPassword, deleteUser, getAuth, GoogleAuthProvider, onAuthStateChanged, sendEmailVerification, sendPasswordResetEmail, setPersistence, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { doc, getDoc, getFirestore, serverTimestamp, setDoc, writeBatch } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const OWNER_EMAIL='shadrat.almn7@gmail.com';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
if(new URLSearchParams(location.search).get('admin')==='1'){
  await auth.authStateReady();
  if(auth.currentUser) await signOut(auth);
}
const clean=(v='')=>v.trim().toLowerCase(),isOwner=(v='')=>clean(v)===OWNER_EMAIL;
const normalizeUsername=(value='')=>clean(value).replace(/^@/,'');
const reservedUsername=(value='')=>/(^|_)(owner|admin|support|staff|shazarat|شذرات|مالك|ادارة|إدارة)(_|$)/i.test(value);
const normalizePhone=(value='')=>{let p=value.replace(/[^\d+]/g,'');if(p.startsWith('00'))p=`+${p.slice(2)}`;if(/^05\d{8}$/.test(p))p=`+966${p.slice(1)}`;if(/^9665\d{8}$/.test(p))p=`+${p}`;return /^\+[1-9]\d{7,14}$/.test(p)?p:null};
const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const errorText=(e)=>{const known={'auth/invalid-credential':'البريد الإلكتروني أو كلمة المرور غير صحيحة.','auth/email-already-in-use':'هذا البريد مستخدم في حساب آخر.','auth/weak-password':'اختر كلمة مرور أقوى لا تقل عن 10 أحرف.','auth/popup-closed-by-user':'أُغلقت نافذة Google قبل إكمال الدخول.','auth/unauthorized-domain':'نطاق الموقع غير مصرح به في Firebase.','auth/operation-not-allowed':'طريقة الدخول غير مفعلة في Firebase.','auth/network-request-failed':'تعذر الاتصال. تحقق من الإنترنت وحاول مجددًا.','permission-denied':'رفضت قاعدة البيانات العملية. تحقق من البيانات وحاول مجددًا.'};return e?.message?.includes('phone-already-used')?'رقم الجوال مستخدم في حساب آخر.':known[e?.code]||'تعذر إكمال العملية الآن. حاول مرة أخرى.'};
async function roleFor(user){if(!user)return null;if(isOwner(user.email)&&user.emailVerified)return'owner';try{const s=await getDoc(doc(db,'users',user.uid));return s.exists()?s.data().role:'student'}catch{return'student'}}
const show=(form,text,type='error')=>{const n=form?.querySelector('[data-auth-message]');if(n){n.textContent=text;n.className=`auth-message ${type}`}};
const destination=async user=>['owner','support'].includes(await roleFor(user))?'admin-analytics.html':'profile.html';
const loginForm=document.querySelector('#login-form');
loginForm?.addEventListener('submit',async(e)=>{e.preventDefault();if(!loginForm.reportValidity())return;const button=loginForm.querySelector('[type=submit]');button.disabled=true;try{await setPersistence(auth,browserLocalPersistence);const c=await signInWithEmailAndPassword(auth,clean(loginForm.email.value),loginForm.password.value);location.href=await destination(c.user)}catch(x){show(loginForm,errorText(x))}finally{button.disabled=false}});
document.querySelector('#google-login')?.addEventListener('click',async(e)=>{const button=e.currentTarget;button.disabled=true;try{await setPersistence(auth,browserLocalPersistence);const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const c=await signInWithPopup(auth,provider);const userRef=doc(db,'users',c.user.uid),snap=await getDoc(userRef);if(!isOwner(c.user.email)&&!snap.exists())await setDoc(userRef,{uid:c.user.uid,email:clean(c.user.email||''),fullName:c.user.displayName||'',username:`student_${c.user.uid.slice(0,6)}`,role:'student',accountStatus:'active',publicProfile:false,xp:0,level:1,profilePending:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});const target=await destination(c.user);if(target.startsWith('admin-'))sessionStorage.setItem('shazarat_admin_reauth',String(Date.now()));location.href=target}catch(x){show(loginForm,errorText(x))}finally{button.disabled=false}});
document.querySelector('#reset-password')?.addEventListener('click',async(e)=>{e.preventDefault();const email=clean(loginForm?.email.value);if(!email)return show(loginForm,'اكتب بريدك الإلكتروني أولًا.');try{await sendPasswordResetEmail(auth,email);show(loginForm,'أرسلنا رابط إعادة تعيين كلمة المرور إلى بريدك.','success')}catch(x){show(loginForm,errorText(x))}});
const registerForm=document.querySelector('#register-form');
registerForm?.addEventListener('submit',async(e)=>{e.preventDefault();if(!registerForm.reportValidity())return;if(registerForm.pass.value!==registerForm.confirm.value)return show(registerForm,'كلمتا المرور غير متطابقتين.');const phone=normalizePhone(registerForm.phone.value);if(!phone)return show(registerForm,'اكتب رقم جوال صحيحًا بصيغة دولية، مثل +9665xxxxxxxx.');const email=clean(registerForm.mail.value),username=normalizeUsername(registerForm.username.value);if(isOwner(email))return show(registerForm,'هذا البريد مخصص لحساب قائم. استخدم تسجيل الدخول.');if(!/^[a-z0-9_]{3,24}$/.test(username))return show(registerForm,'الاسم الظاهر من 3 إلى 24 حرفًا إنجليزيًا أو رقمًا أو _.');if(reservedUsername(username))return show(registerForm,'هذا الاسم محجوز للإدارة، اختر اسمًا آخر.');const button=registerForm.querySelector('[type=submit]');button.disabled=true;let created=null;try{await setPersistence(auth,browserLocalPersistence);const phoneHash=await digest(phone);created=await createUserWithEmailAndPassword(auth,email,registerForm.pass.value);await updateProfile(created.user,{displayName:registerForm.full.value.trim()});const batch=writeBatch(db);batch.set(doc(db,'phoneReservations',phoneHash),{uid:created.user.uid,createdAt:serverTimestamp()});batch.set(doc(db,'usernameReservations',username),{uid:created.user.uid,createdAt:serverTimestamp()});batch.set(doc(db,'users',created.user.uid),{uid:created.user.uid,email,fullName:registerForm.full.value.trim(),username,phoneHash,phoneLast4:phone.slice(-4),role:'student',accountStatus:'active',publicProfile:false,xp:0,level:1,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await batch.commit();await sendEmailVerification(created.user);show(registerForm,'تم إنشاء الحساب. أرسلنا رسالة تحقق إلى بريدك، وسيتم نقلك إلى حسابك.','success');setTimeout(()=>location.href='profile.html',900)}catch(x){if(created?.user)try{await deleteUser(created.user)}catch{}show(registerForm,x?.code==='permission-denied'?'رقم الجوال أو الاسم الظاهر مستخدم بالفعل.':errorText(x))}finally{button.disabled=false}});
if(document.body.dataset.role==='owner'){document.documentElement.classList.add('auth-checking');onAuthStateChanged(auth,async user=>{if(!user||!['owner','support'].includes(await roleFor(user))){location.replace('login.html?admin=1');return}document.documentElement.classList.remove('auth-checking')})}
document.querySelectorAll('[data-sign-out]').forEach(b=>b.addEventListener('click',async()=>{await signOut(auth);location.replace('login.html')}));
export{auth,db,roleFor,normalizePhone,digest};
