import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { browserLocalPersistence, browserSessionPersistence, createUserWithEmailAndPassword, getAuth, GoogleAuthProvider, onAuthStateChanged, sendEmailVerification, sendPasswordResetEmail, setPersistence, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { doc, getDoc, getFirestore, serverTimestamp, setDoc } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const OWNER_EMAIL='shadrat.almn7@gmail.com';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const clean=(v='')=>v.trim().toLowerCase(),isOwner=(v='')=>clean(v)===OWNER_EMAIL;
const errorText=(e)=>({'auth/invalid-credential':'البريد الإلكتروني أو كلمة المرور غير صحيحة.','auth/email-already-in-use':'هذا البريد مستخدم في حساب آخر.','auth/weak-password':'اختر كلمة مرور أقوى لا تقل عن 10 أحرف.','auth/popup-closed-by-user':'أُغلقت نافذة Google قبل إكمال الدخول.','auth/unauthorized-domain':'يجب إضافة نطاق الموقع إلى النطاقات المصرح بها في Firebase.','auth/operation-not-allowed':'طريقة الدخول هذه تحتاج تفعيلها من Firebase أولًا.','auth/network-request-failed':'تعذر الاتصال. تحقق من الإنترنت وحاول مجددًا.'}[e?.code]||'تعذر إكمال العملية الآن. حاول مرة أخرى.');
async function roleFor(user){if(!user)return null;if(isOwner(user.email)&&user.emailVerified)return'owner';try{const s=await getDoc(doc(db,'users',user.uid));return s.exists()?s.data().role:'student'}catch{return'student'}}
const show=(form,text,type='error')=>{const n=form?.querySelector('[data-auth-message]');if(n){n.textContent=text;n.className=`auth-message ${type}`}};
const loginForm=document.querySelector('#login-form');
loginForm?.addEventListener('submit',async(e)=>{e.preventDefault();if(!loginForm.reportValidity())return;const email=clean(loginForm.email.value);if(isOwner(email))return show(loginForm,'دخول المالك يتم بزر Google فقط لحماية لوحة الإدارة والتحقق بخطوتين من حساب Google.');try{await setPersistence(auth,browserLocalPersistence);const c=await signInWithEmailAndPassword(auth,email,loginForm.password.value);location.href=['owner','support'].includes(await roleFor(c.user))?'admin-analytics.html':'profile.html'}catch(x){show(loginForm,errorText(x))}});
document.querySelector('#admin-google-login')?.addEventListener('click',async()=>{try{await setPersistence(auth,browserSessionPersistence);const c=await signInWithPopup(auth,new GoogleAuthProvider()),role=await roleFor(c.user);if(!['owner','support'].includes(role)){await signOut(auth);return show(loginForm,'هذا الحساب غير مصرح له بدخول الإدارة.')}location.href='admin-analytics.html'}catch(e){show(loginForm,errorText(e))}});
document.querySelector('#reset-password')?.addEventListener('click',async(e)=>{e.preventDefault();const email=clean(loginForm?.email.value);if(!email)return show(loginForm,'اكتب بريدك الإلكتروني أولًا.');try{await sendPasswordResetEmail(auth,email);show(loginForm,'أرسلنا رابط إعادة تعيين كلمة المرور إلى بريدك.','success')}catch(x){show(loginForm,errorText(x))}});
const registerForm=document.querySelector('#register-form');
registerForm?.addEventListener('submit',async(e)=>{e.preventDefault();if(!registerForm.reportValidity())return;if(registerForm.pass.value!==registerForm.confirm.value)return show(registerForm,'كلمتا المرور غير متطابقتين.');const email=clean(registerForm.mail.value);if(isOwner(email))return show(registerForm,'حساب المالك لا يُنشأ من صفحة التسجيل العامة.');try{await setPersistence(auth,browserLocalPersistence);const c=await createUserWithEmailAndPassword(auth,email,registerForm.pass.value);await updateProfile(c.user,{displayName:registerForm.full.value.trim()});await setDoc(doc(db,'users',c.user.uid),{uid:c.user.uid,email,fullName:registerForm.full.value.trim(),username:registerForm.username.value.trim(),phone:registerForm.phone.value.trim(),role:'student',accountStatus:'active',publicProfile:false,xp:0,level:1,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await sendEmailVerification(c.user);show(registerForm,'تم إنشاء الحساب. تحقق من بريدك الإلكتروني ثم سجّل الدخول.','success')}catch(x){show(registerForm,errorText(x))}});
if(document.body.dataset.role==='owner'){document.documentElement.classList.add('auth-checking');onAuthStateChanged(auth,async user=>{if(!user||!['owner','support'].includes(await roleFor(user))){location.replace('login.html');return}document.documentElement.classList.remove('auth-checking')})}
document.querySelectorAll('[data-sign-out]').forEach(b=>b.addEventListener('click',async()=>{await signOut(auth);location.replace('login.html')}));
export{auth,db,roleFor};
