import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,doc,getDocs,getFirestore,limit,orderBy,query,updateDoc,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=document.createElement('style');style.textContent=`.shz-alert-stack{position:fixed;top:84px;left:18px;z-index:1100;width:min(390px,calc(100% - 36px));display:grid;gap:10px}.shz-alert{background:#fffdf8;border:1px solid #ded5c7;border-radius:18px;padding:15px 16px;box-shadow:0 16px 40px #0002;direction:rtl}.shz-alert b{display:block;color:#176b4b;margin-bottom:5px}.shz-alert p{margin:0;color:#52645c;line-height:1.7;font-size:13px}.shz-alert button{margin-top:9px;border:0;background:#e8f3ed;color:#176b4b;border-radius:10px;padding:7px 11px;font:inherit;font-weight:800;cursor:pointer}`;document.head.appendChild(style);
const stack=document.createElement('div');stack.className='shz-alert-stack';document.body.appendChild(stack);const shown=new Set(JSON.parse(sessionStorage.getItem('shz_seen_alerts')||'[]'));
function remember(id){shown.add(id);sessionStorage.setItem('shz_seen_alerts',JSON.stringify([...shown].slice(-50)))}
function showItem(id,title,body,onClose){if(shown.has(id))return;const el=document.createElement('article');el.className='shz-alert';el.innerHTML=`<b>${esc(title)}</b><p>${esc(body)}</p><button type="button">حسنًا</button>`;el.querySelector('button').onclick=async()=>{remember(id);el.remove();try{await onClose?.()}catch{}};stack.appendChild(el)}
async function loadGeneral(){try{const s=await getDocs(query(collection(db,'announcements'),where('publishStatus','==','published'),orderBy('createdAt','desc'),limit(3)));s.docs.reverse().forEach(d=>{const x=d.data();showItem(`a:${d.id}`,x.title,x.body)})}catch(e){console.warn('announcements unavailable',e)}}
loadGeneral();
onAuthStateChanged(auth,async user=>{if(!user)return;try{const s=await getDocs(query(collection(db,'users',user.uid,'notifications'),orderBy('createdAt','desc'),limit(8)));s.docs.reverse().forEach(d=>{const x=d.data();if(x.read)return;showItem(`n:${d.id}`,x.title||'تنبيه من شذرات',x.body||'',()=>updateDoc(doc(db,'users',user.uid,'notifications',d.id),{read:true}))})}catch(e){console.warn('personal notifications unavailable',e)}});
