import { getApp, getApps, initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { doc, getDoc, getFirestore, serverTimestamp, writeBatch } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const modal=document.querySelector('#profile-edit-modal'),form=document.querySelector('#profile-edit-form');let loadedProfile={};
const reserved=(value='')=>/(^|_)(owner|admin|support|staff|shazarat|شذرات|مالك|ادارة|إدارة)(_|$)/i.test(value);
function setModal(open){modal?.classList.toggle('is-open',open);modal?.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open)}
document.querySelectorAll('.student-edit,[data-demo="edit-profile"]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();if(!auth.currentUser)return;for(const key of['fullName','username','location','studyLevel'])if(form?.elements[key])form.elements[key].value=loadedProfile[key]||'';if(form?.elements.email)form.elements.email.value=auth.currentUser.email||'';if(form?.elements.phone)form.elements.phone.value=loadedProfile.phoneLast4?`•••• ${loadedProfile.phoneLast4}`:'';setModal(true)}));
modal?.querySelectorAll('.profile-modal-close,.profile-modal-cancel').forEach(button=>button.addEventListener('click',()=>setModal(false)));
document.documentElement.classList.add('auth-checking');
onAuthStateChanged(auth,async user=>{
  if(!user){location.replace(`login.html?next=${encodeURIComponent('profile.html')}`);return}
  document.querySelectorAll('a[href="login.html"],a[href="register.html"]').forEach(a=>{a.hidden=true;a.style.setProperty('display','none','important')});
  const nav=document.querySelector('header .nav');if(nav&&!nav.querySelector('[data-profile-logout]')){const out=document.createElement('button');out.type='button';out.dataset.profileLogout='';out.textContent='تسجيل الخروج';out.style.cssText='border:0;border-radius:13px;padding:11px 15px;background:#b42318;color:#fff;font:inherit;font-weight:900;cursor:pointer';out.addEventListener('click',async()=>{await signOut(auth);location.replace('index.html')});nav.appendChild(out)}
  const snap=await getDoc(doc(db,'users',user.uid)),p=snap.exists()?snap.data():{};loadedProfile=p;
  const values={fullName:p.fullName||user.displayName||'طالب شذرات',username:p.username||`student_${user.uid.slice(0,6)}`,email:user.email||'',phone:p.phoneLast4?`•••• ${p.phoneLast4}`:'لم تتم إضافته',location:p.location||'',studyLevel:p.studyLevel||''};
  document.querySelectorAll('[data-profile-value]').forEach(el=>{const k=el.dataset.profileValue;el.textContent=k==='username'?`@${values[k]}`:(values[k]||'لم يتم تحديدها')});
  const h=document.querySelector('.student-name h2'),handle=document.querySelector('.student-name .handle');if(h)h.textContent=`مرحبًا، ${values.fullName}`;if(handle)handle.textContent=`@${values.username}`;
  document.documentElement.classList.remove('auth-checking');
});
form?.addEventListener('submit',async event=>{event.preventDefault();const user=auth.currentUser;if(!user)return;const username=String(form.username.value||'').trim().toLowerCase().replace(/^@/,'');const message=form.querySelector('.profile-form-note');if(!/^[a-z0-9_]{3,24}$/.test(username)){message.textContent='الاسم الظاهر من 3 إلى 24 حرفًا إنجليزيًا أو رقمًا أو _.';return}if(reserved(username)){message.textContent='هذا الاسم محجوز للإدارة، اختر اسمًا آخر.';return}try{const batch=writeBatch(db);if(username!==loadedProfile.username)batch.set(doc(db,'usernameReservations',username),{uid:user.uid,createdAt:serverTimestamp()});batch.update(doc(db,'users',user.uid),{fullName:form.fullName.value.trim(),username,location:form.location.value.trim(),studyLevel:form.studyLevel.value,updatedAt:serverTimestamp()});await batch.commit();loadedProfile={...loadedProfile,fullName:form.fullName.value.trim(),username,location:form.location.value.trim(),studyLevel:form.studyLevel.value};message.textContent='تم حفظ الملف بنجاح.';document.querySelectorAll('[data-profile-value]').forEach(el=>{const key=el.dataset.profileValue;if(key==='username')el.textContent=`@${username}`;else if(loadedProfile[key]!==undefined)el.textContent=loadedProfile[key]||'لم يتم تحديدها'});document.querySelector('.student-name h2').textContent=`مرحبًا، ${loadedProfile.fullName}`;document.querySelector('.student-name .handle').textContent=`@${username}`;setTimeout(()=>setModal(false),600)}catch(error){message.textContent=error?.code==='permission-denied'?'هذا الاسم مستخدم بالفعل أو لا تملك صلاحية التعديل.':'تعذر حفظ التعديلات. حاول مرة أخرى.'}});
