import { getApp, getApps, initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { doc, getDoc, getFirestore, runTransaction, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const modal=document.querySelector('#profile-edit-modal'),form=document.querySelector('#profile-edit-form');let loadedProfile={};
const reserved=(value='')=>/(^|_)(owner|admin|support|staff|shazarat|شذرات|مالك|ادارة|إدارة)(_|$)/i.test(value);
const msg=()=>form?.querySelector('.profile-form-note');
function setModal(open){modal?.classList.toggle('is-open',open);modal?.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open)}
function render(user,p){loadedProfile=p;const values={fullName:p.fullName||user.displayName||'طالب شذرات',username:p.username||`student_${user.uid.slice(0,6)}`,email:user.email||'',phone:p.phoneLast4?`•••• ${p.phoneLast4}`:'لم تتم إضافته',location:p.location||'',studyLevel:p.studyLevel||''};document.querySelectorAll('[data-profile-value]').forEach(el=>{const k=el.dataset.profileValue;el.textContent=k==='username'?`@${values[k]}`:(values[k]||'لم يتم تحديدها')});const h=document.querySelector('.student-name h2'),handle=document.querySelector('.student-name .handle');if(h)h.textContent=`مرحبًا، ${values.fullName}`;if(handle)handle.textContent=`@${values.username}`}
document.querySelectorAll('.student-edit,[data-demo="edit-profile"]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();if(!auth.currentUser)return;for(const key of['fullName','username','location','studyLevel'])if(form?.elements[key])form.elements[key].value=loadedProfile[key]||'';if(form?.elements.email)form.elements.email.value=auth.currentUser.email||'';if(form?.elements.phone)form.elements.phone.value=loadedProfile.phoneLast4?`•••• ${loadedProfile.phoneLast4}`:'';if(msg())msg().textContent='يتم الحفظ في حسابك مباشرة. البريد ورقم الجوال لا يتغيران من هذه الصفحة.';setModal(true)}));
modal?.querySelectorAll('.profile-modal-close,.profile-modal-cancel').forEach(button=>button.addEventListener('click',()=>setModal(false)));
document.documentElement.classList.add('auth-checking');
onAuthStateChanged(auth,async user=>{
  if(!user){location.replace(`login.html?next=${encodeURIComponent('profile.html')}`);return}
  document.querySelectorAll('a[href="login.html"],a[href="register.html"]').forEach(a=>{a.hidden=true;a.style.setProperty('display','none','important')});
  const nav=document.querySelector('header .nav');if(nav&&!nav.querySelector('[data-profile-logout]')){const out=document.createElement('button');out.type='button';out.dataset.profileLogout='';out.textContent='تسجيل الخروج';out.style.cssText='border:0;border-radius:13px;padding:11px 15px;background:#b42318;color:#fff;font:inherit;font-weight:900;cursor:pointer';out.addEventListener('click',async()=>{await signOut(auth);location.replace('index.html')});nav.appendChild(out)}
  try{const snap=await getDoc(doc(db,'users',user.uid));render(user,snap.exists()?snap.data():{})}catch(e){console.error(e);if(msg())msg().textContent='تعذر تحميل بيانات الحساب.'}
  document.documentElement.classList.remove('auth-checking');
});
form?.addEventListener('submit',async event=>{event.preventDefault();const user=auth.currentUser;if(!user)return;const username=String(form.username.value||'').trim().toLowerCase().replace(/^@/,'');const message=msg();if(!/^[a-z0-9_]{3,24}$/.test(username)){message.textContent='الاسم الظاهر من 3 إلى 24 حرفًا إنجليزيًا أو رقمًا أو _.';return}if(reserved(username)){message.textContent='هذا الاسم محجوز للإدارة، اختر اسمًا آخر.';return}const fullName=form.fullName.value.trim(),locationValue=form.location.value.trim(),studyLevel=form.studyLevel.value,oldUsername=String(loadedProfile.username||'').trim().toLowerCase();const submit=form.querySelector('[type="submit"]');submit.disabled=true;message.textContent='جارٍ الحفظ…';try{
  await runTransaction(db,async tx=>{const userRef=doc(db,'users',user.uid),newRef=doc(db,'usernameReservations',username),oldRef=oldUsername?doc(db,'usernameReservations',oldUsername):null,newSnap=await tx.get(newRef);let oldSnap=null;if(oldRef&&oldUsername!==username)oldSnap=await tx.get(oldRef);if(newSnap.exists()&&newSnap.data().uid!==user.uid)throw new Error('username-taken');if(oldSnap?.exists()&&oldSnap.data().uid===user.uid)tx.delete(oldRef);tx.set(newRef,{uid:user.uid,updatedAt:serverTimestamp()},{merge:true});tx.update(userRef,{fullName,username,location:locationValue,studyLevel,updatedAt:serverTimestamp()})});
  if(user.displayName!==fullName)await updateProfile(user,{displayName:fullName});loadedProfile={...loadedProfile,fullName,username,location:locationValue,studyLevel};render(user,loadedProfile);message.textContent='تم حفظ الملف بنجاح.';setTimeout(()=>setModal(false),700)
}catch(error){console.error(error);message.textContent=error?.message==='username-taken'?'اسم المستخدم مستخدم بالفعل. اختر اسمًا آخر.':error?.code==='permission-denied'?'رفضت قاعدة البيانات التعديل. يلزم نشر قواعد Firebase الجديدة.':'تعذر حفظ التعديلات. حاول مرة أخرى.'}finally{submit.disabled=false}});
