import { getApp,getApps,initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { collection,doc,getDoc,getDocs,getFirestore,serverTimestamp,setDoc } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { getAuth,onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { firebaseConfig } from './firebase-config.js';
import { mergeScholarships } from './scholarship-catalog.js';
const css=document.createElement('link');css.rel='stylesheet';css.href='scholarships-admin.css?v=2';document.head.appendChild(css);
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const addButton=document.querySelector('.admin-title .primary'),tbody=document.querySelector('.admin-table tbody'),metrics=[...document.querySelectorAll('.metric b')];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=v=>String(v||'').split('\n').map(x=>x.trim()).filter(Boolean);
const slugify=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,'-').replace(/^-|-$/g,'');
let records=[];
document.body.insertAdjacentHTML('beforeend',`<div class="scholarship-modal" hidden><div class="scholarship-modal-backdrop" data-close></div><section class="scholarship-form-card" role="dialog" aria-modal="true"><div class="form-head"><div><small>قالب تلقائي متكامل</small><h2>بيانات المنحة</h2></div><button type="button" data-close>×</button></div><form id="scholarship-form"><input type="hidden" name="originalSlug"><div class="form-grid"><label>اسم المنحة*<input name="title" required minlength="3"></label><label>الرابط المختصر*<input name="slug" dir="ltr" required pattern="[a-z0-9-]+"></label><label>الدولة*<input name="country" required></label><label>الجهة المقدمة<input name="provider"></label><label class="wide">الوصف الظاهر في البطاقة*<textarea name="shortDescription" required minlength="10" maxlength="500"></textarea></label><label class="wide">نبذة صفحة التفاصيل<textarea name="overview"></textarea></label><label>نوع التمويل<input name="funding"></label><label>المراحل الدراسية<input name="studyLevels" placeholder="بكالوريوس، ماجستير"></label><label>فتح التقديم<input name="openDate" type="date"></label><label>الموعد النهائي<input name="deadline" type="date"></label><label>الحالة الظاهرة<input name="statusLabel" placeholder="مفتوحة / تفتح قريبًا"></label><label>حالة النشر<select name="publishStatus"><option value="draft">مسودة</option><option value="published">منشورة</option><option value="hidden">مخفية</option><option value="archived">مؤرشفة</option></select></label><label class="wide">شروط الأهلية — كل شرط في سطر<textarea name="eligibility"></textarea></label><label class="wide">المستندات — كل مستند في سطر<textarea name="documents"></textarea></label><label class="wide">خطوات التقديم — كل خطوة في سطر<textarea name="steps"></textarea></label><label>المصدر الرسمي<input name="officialUrl" type="url" dir="ltr"></label><label>رابط التقديم<input name="applyUrl" type="url" dir="ltr"></label><label class="check"><input name="featured" type="checkbox"> منحة مميزة</label></div><p class="form-message" aria-live="polite"></p><div class="form-actions"><button class="btn primary" type="submit">حفظ وتحديث الموقع</button><button class="btn" type="button" data-close>إلغاء</button></div></form></section></div>`);
const modal=document.querySelector('.scholarship-modal'),form=document.querySelector('#scholarship-form'),message=form.querySelector('.form-message');
function openForm(item={}){form.reset();form.originalSlug.value=item.slug||'';for(const [k,v] of Object.entries(item)){const f=form.elements[k];if(!f)continue;if(f.type==='checkbox')f.checked=!!v;else f.value=Array.isArray(v)?v.join(k==='studyLevels'?'، ':'\n'):(v??'')}form.slug.readOnly=!!item.slug;modal.hidden=false;document.body.classList.add('menu-open')}
function closeForm(){modal.hidden=true;document.body.classList.remove('menu-open');message.textContent=''}
modal.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeForm));
form.title.addEventListener('input',()=>{if(!form.originalSlug.value)form.slug.value=slugify(form.title.value)});
addButton?.addEventListener('click',()=>openForm());
function render(){metrics[0].textContent=records.length;metrics[1].textContent=records.filter(x=>x.publishStatus==='published').length;metrics[2].textContent=records.filter(x=>x.publishStatus==='draft').length;metrics[3].textContent=records.filter(x=>['hidden','archived'].includes(x.publishStatus)).length;tbody.innerHTML=records.map(s=>`<tr><td data-label="المنحة"><b>${esc(s.title)}</b><br><small>${esc(s.country||'—')}</small></td><td data-label="الحالة">${esc(s.statusLabel||'—')}</td><td data-label="النشر"><span class="status-pill status-${esc(s.publishStatus)}">${({published:'منشورة',draft:'مسودة',hidden:'مخفية',archived:'مؤرشفة'})[s.publishStatus]||s.publishStatus}</span></td><td data-label="المشاهدات">${Number(s.viewCount||0).toLocaleString('ar')}</td><td data-label="الحفظ">${Number(s.saveCount||0).toLocaleString('ar')}</td><td data-label="جودة المحتوى">${[s.officialUrl,s.shortDescription,s.funding,s.studyLevels?.length,s.facts?.length].filter(Boolean).length} / 5</td><td data-label="المحرر">Owner</td><td data-label="إجراء"><button class="table-action" data-edit="${esc(s.slug)}">تعديل</button></td></tr>`).join('');tbody.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openForm(records.find(x=>x.slug===b.dataset.edit))))}
async function load(){tbody.innerHTML='<tr><td colspan="8">جارٍ تحميل جميع المنح…</td></tr>';const snap=await getDocs(collection(db,'scholarships'));records=mergeScholarships(snap.docs.map(d=>d.data()));render()}
form.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form)),slug=form.originalSlug.value||slugify(data.slug||data.title);message.textContent='جارٍ حفظ البطاقة والصفحة…';const scholarship={slug,title:data.title.trim(),country:data.country.trim(),provider:data.provider.trim(),shortDescription:data.shortDescription.trim(),overview:data.overview.trim(),funding:data.funding.trim(),studyLevels:data.studyLevels.split(/[،,]/).map(x=>x.trim()).filter(Boolean),openDate:data.openDate||null,deadline:data.deadline||null,statusLabel:data.statusLabel.trim(),publishStatus:data.publishStatus,eligibility:lines(data.eligibility),documents:lines(data.documents),steps:lines(data.steps),officialUrl:data.officialUrl.trim(),applyUrl:data.applyUrl.trim(),legacyUrl:null,featured:form.featured.checked,updatedAt:serverTimestamp()};try{const ref=doc(db,'scholarships',slug),old=await getDoc(ref);if(!old.exists())scholarship.createdAt=serverTimestamp();await setDoc(ref,scholarship,{merge:true});message.textContent='تم الحفظ؛ البطاقة وصفحة التفاصيل تتحدثان تلقائيًا.';setTimeout(async()=>{closeForm();await load()},700)}catch(err){console.error(err);message.textContent=err.code==='permission-denied'?'رفضت الصلاحية: ادخل بحساب المالك ثم حاول مجددًا.':'تعذر الحفظ؛ حاول مجددًا.'}});
onAuthStateChanged(auth,user=>{if(user)load().catch(e=>{console.error(e);tbody.innerHTML='<tr><td colspan="8">تعذر تحميل المنح. أعد المحاولة.</td></tr>'})});
