export const scholarshipCatalog = [
  {slug:'open-doors',title:'أولمبياد Open Doors',country:'روسيا',provider:'Global Universities Association',shortDescription:'مسابقة دولية مجانية عبر الإنترنت تتيح للفائزين الدراسة دون رسوم وفق المسار والمرحلة.',funding:'إعفاء من الرسوم للفائزين',studyLevels:['بكالوريوس','ماجستير','دكتوراه','ما بعد الدكتوراه'],openDate:'2026-08-20',deadline:'2026-11-01',statusLabel:'تفتح قريبًا',publishStatus:'published',featured:true,sortOrder:1,legacyUrl:'open-doors.html',facts:[['فتح التسجيل','20 أغسطس 2026'],['إغلاق التسجيل','1 نوفمبر 2026'],['المرحلة الأولى','ملف إنجاز + اختبار تمهيدي'],['التمويل','دراسة دون رسوم للفائزين']],officialUrl:'https://od.globaluni.ru/',documents:['هوية أو جواز سفر','وثائق المرحلة الدراسية','ملف الإنجازات وفق المسار'],steps:['إنشاء الحساب واختيار المسار','إكمال الملف والاختبار التمهيدي','رفع ملف الإنجازات','الانتقال للمرحلة الثانية عند التأهل']},
  {slug:'education-in-russia',title:'Education in Russia',country:'روسيا',provider:'الحكومة الروسية',shortDescription:'مسار التقديم الرسمي على مقاعد الحكومة الروسية للطلاب الأجانب مع مراجعة محلية حسب دولة المتقدم.',funding:'كوتة حكومية',studyLevels:['بكالوريوس','ماجستير','دكتوراه'],openDate:null,deadline:null,statusLabel:'حسب الدولة',publishStatus:'published',featured:true,sortOrder:2,legacyUrl:'education-in-russia.html',facts:[['الموسم القادم','بانتظار الإعلان'],['الموعد','يختلف حسب الدولة'],['التقديم','مجاني رسميًا'],['المراحل','طلب ← ترشيح ← جامعة']],officialUrl:'https://education-in-russia.com/',documents:['جواز السفر','الشهادة وكشف الدرجات','الترجمة المطلوبة حسب الجهة'],steps:['إنشاء حساب رسمي','تعبئة الطلب واختيار الجامعات','الفرز والاختبارات المحلية','الترشيح واستكمال الجامعة']},
  {slug:'turkiye-scholarships',title:'منحة الحكومة التركية',country:'تركيا',provider:'Türkiye Scholarships',shortDescription:'برنامج حكومي تنافسي يشمل القبول الجامعي والرسوم والسكن والتأمين والراتب وفق شروط الموسم.',funding:'ممولة بالكامل',studyLevels:['دبلوم متوسط','بكالوريوس','ماجستير','دكتوراه'],openDate:'2026-01-10',deadline:'2026-02-20',statusLabel:'مغلقة لموسم 2026',publishStatus:'published',sortOrder:3,legacyUrl:'turkiye-scholarships.html',facts:[['فتح موسم 2026','10 يناير 2026'],['الإغلاق','20 فبراير 2026'],['التغطية','رسوم + سكن + راتب'],['القادم','بانتظار الإعلان']],officialUrl:'https://www.turkiyeburslari.gov.tr/'},
  {slug:'stipendium-hungaricum',title:'Stipendium Hungaricum',country:'المجر',provider:'Tempus Public Foundation',shortDescription:'منحة حكومية مجرية تشمل الإعفاء ومخصصًا شهريًا وسكنًا أو مساهمة وتأمينًا وفق البرنامج والدولة.',funding:'ممولة',studyLevels:['بكالوريوس','ماجستير','دكتوراه'],openDate:null,deadline:'2026-01-15',statusLabel:'انتهى موعد 2026',publishStatus:'published',sortOrder:4,legacyUrl:'stipendium-hungaricum.html',facts:[['موعد 2026','15 يناير 2026'],['الترشيح','حسب دولة الإرسال'],['التغطية','رسوم + مخصص'],['السكن','سكن أو مساهمة']],officialUrl:'https://stipendiumhungaricum.hu/'},
  {slug:'hse-scholarship',title:'منح HSE University',country:'روسيا',provider:'HSE University',shortDescription:'فرص منح كاملة أو جزئية ومسارات عبر الكوتة الحكومية وOpen Doors للطلاب الدوليين.',funding:'كامل أو جزئي',studyLevels:['بكالوريوس','ماجستير','دكتوراه'],openDate:null,deadline:'2026-03-13',statusLabel:'راجع المسار',publishStatus:'published',sortOrder:5,legacyUrl:'hse-scholarship.html',facts:[['منحة HSE','حتى 13 مارس 2026'],['المسارات','HSE + كوتة + Open Doors'],['التمويل','كامل أو جزئي'],['المدينة','موسكو وفروع أخرى']],officialUrl:'https://www.hse.ru/en/'},
  {slug:'rudn-scholarship',title:'جامعة RUDN',country:'روسيا',provider:'RUDN University',shortDescription:'مسارات للطلاب الدوليين عبر الكوتة الحكومية الروسية أو القبول المباشر وفق البرنامج.',funding:'حسب المسار',studyLevels:['بكالوريوس','ماجستير','دكتوراه'],openDate:null,deadline:null,statusLabel:'الموعد حسب المسار',publishStatus:'published',sortOrder:6,legacyUrl:'rudn-scholarship.html',facts:[['المسار الأول','الكوتة الحكومية'],['المسار الثاني','قبول مباشر'],['المواعيد','حسب المسار والبرنامج'],['الموقع','موسكو']],officialUrl:'https://www.rudn.ru/'},
  {slug:'nsu-scholarship',title:'جامعة نوفوسيبيرسك NSU',country:'روسيا',provider:'Novosibirsk State University',shortDescription:'فرص للطلاب الدوليين عبر الكوتة الروسية وOpen Doors والقبول الدولي المباشر.',funding:'حسب المسار',studyLevels:['بكالوريوس','ماجستير','دكتوراه'],openDate:null,deadline:null,statusLabel:'الموعد حسب المسار',publishStatus:'published',sortOrder:7,legacyUrl:'nsu-scholarship.html',facts:[['المسارات','كوتة + Open Doors'],['القبول','دولي مباشر أيضًا'],['المواعيد','تختلف حسب المسار'],['المدينة','نوفوسيبيرسك']],officialUrl:'https://english.nsu.ru/'}
];
export function mergeScholarships(remote=[]){const map=new Map(scholarshipCatalog.map(item=>[item.slug,{...item}]));remote.forEach(item=>map.set(item.slug,{...(map.get(item.slug)||{}),...item}));return [...map.values()].sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999))}
